# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
            ],
            managers=[
                ('friendManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='friends.Friend')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
            ],
        ),
    ]
